// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Statistic.Infrastructure.Data;

#nullable disable

namespace Statistic.Infrastructure.Migrations
{
    [DbContext(typeof(StatisticDbContext))]
    [Migration("20240216000458_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Statistic.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FederalState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("Statistic.Domain.Entities.Visitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("Statistic.Domain.Entities.VisitorInterests", b =>
                {
                    b.Property<Guid>("VisitorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Interest")
                        .HasColumnType("varchar(255)");

                    b.HasKey("VisitorId", "Interest");

                    b.ToTable("VisitorInterests");
                });

            modelBuilder.Entity("Statistic.Domain.Entities.Visitor", b =>
                {
                    b.HasOne("Statistic.Domain.Entities.Address", "Address")
                        .WithOne("Visitor")
                        .HasForeignKey("Statistic.Domain.Entities.Visitor", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Statistic.Domain.Entities.VisitorInterests", b =>
                {
                    b.HasOne("Statistic.Domain.Entities.Visitor", "Visitor")
                        .WithMany("VisitorInterests")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("Statistic.Domain.Entities.Address", b =>
                {
                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("Statistic.Domain.Entities.Visitor", b =>
                {
                    b.Navigation("VisitorInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
